### ISSUE TITLE
Gather requirements for recording search data and meta data

### ISSUE THREAD

**Issue by tendayichakanyuka** [bcgov/ppr-deprecated#324]
We need to gather requirements for gathering search data and meta data. What we need to determine:
- [ ] The comprehensive list of data and meta data to be capture and stored
- [ ] Why this is important to the search... I suspect this information could be retrieved and used somehow later but, not sure when, why, or how
- [ ] What information needs to be recorded
- [ ] How long we are expected to keep this record
- [ ] Who can/cannot see this record

**Comment by LivMac-Git** [comment]
@tendayichakanyuka Will require further input and clarification from you on a strategic approach and other details.
