### ISSUE TITLE
Testing infrastructure

### ISSUE THREAD

**Issue by rstens** [bcgov/ppr-deprecated#340]
The infrastructure consists of:

- [x] All unit/integration testing scripts running locally (developer responsibility)
- [ ] All integration testing scripts running locally (developer responsibility)
- [x] Unit/integration tests running in GitHub actions
- [ ] Unit/integration tests running in OpenShift Pipelines
- [x] Static code checking through linting, sonarscan, coverage +reports
- [x] sign up for SonarCloud, CodeCov
- [x] Operational via SonarCloud and OpenShift SonarQube (discussion on risks of dependency on cloud services)
- [x] Automated functional test framework
- [x] Be able to run local, openshift and BrowserStack
- [ ] Reporting infrastructure - Collection of results and integration with issue management system.
- [ ] Automated or efficient component version management system
- [x] Project sign up for BrowserStack (free) (store secrets in OpenShift)

Solutions for: 
- [ ] Accessibility Scan, 
- [ ] OWASP Zap scan integration, 
- [ ] Performance Testing (JMeter),

**Comment by tendayichakanyuka** [comment]
@rstens is the plan to complete this during Sprint 22?

**Comment by rstens** [comment]
No just **ppr #349 Automated functional test framework Setup**
