### ISSUE TITLE
SP 25 Retro - Mar 17

### ISSUE THREAD

**Issue by Bryce13Reid** [bcgov/ppr-deprecated#793]
#### Keep Doing
- [x] Supportive PO setting the bar higher ++ **2
- Refining the backlog
- Fuller backlog coming with long range plans
- The evolution of the product this sprint was fantastic!
- collaboration
- We have a better long term vision for where we are heading
- Getting more organized, guidance is appreciated
- Team is getting a lot of work done, in spite of some conditions 
- We have a much clearer picture of business requirements
- People understand much more of the application, on a much deeper level.
- Demo went really well.  Even the technical part was clear and helpful.
#### Slowing us down
- [x] Meetings tend to start late, stray off topic, and go long****4
- [x] Need to see faces of co-workers now and then****4
- [x] Confusion about who is responsible for requirements.  Sometimes information from SM, BA & SMEs conflicts. *** 3
- [x] Tickets are becoming too dense in their requirements *** 3
- [x] No tech debt in sprint* 1
- [x] UX/UI not given lead time before dev starts* 1
- [x] Lack of lead time for UI design *1
- [x] Still no cohesive structure for tickets*1 
- [x] Lack of a concrete plan for IMS DB to Oracle: Including architecture, approach, workload, roles etc.* 1
- Way of working remotely.  Need to all be fully engaged.
- Team cohesion is it ok? Now that we are remote this is not important for current consideration.
- Resource availability for testing (UAT)
- Backlog still needs more grooming 
- The work planned is 3 projects (Conversion, refitting, new development) within 2 months. Each of them is strongly dependent on the previous step. The planned 2 months is likely not enough time.
- Team communication and appropriate channels/venues (especially when we consider our now remote standard)
- Design handoff needs to be refined/defined
- Planning for IMS DB to Oracle not very clear.
#### Blocking
- [x] Lack of awareness regarding where we are vs where we said we would be.***3
- Estimation 
- [x] **For IMS DB to Oracle: The quality and availability of the current environments is inadequate and needs to be addressed for PPR not to be unduly impacted by having to work with old data in environments that cannot be updated because others are dependent on it. \*1**
- Mid sprint checking
